name: ArmorStandTools

main: de.iani.ast.ArmorStandTools
softdepend: [WorldEdit, WorldGuard]
version: ${version}

author: Brokkonaut
website: https://github.com/Cubeside/ArmorStandTools
description: ArmorStandTools
api-version: 1.21